import os
import json
import glob

# Configuration
SOURCE_DIR = "Sources/Resources"
OUTPUT_FILE = "Sources/Models/ContentKeys.swift"

def escape_string(s):
    if not s:
        return ""
    # Escape backslashes first, then double quotes, newlines, etc.
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '')

def generate_swift_keys():
    print(f"Scanning {SOURCE_DIR} for JSON files...")
    
    json_files = glob.glob(os.path.join(SOURCE_DIR, "*.json"))
    
    strings_to_localize = []
    
    # Track unique strings to avoid duplicates in the localized file (reduces file size)
    seen_strings = set()

    for file_path in json_files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                
                # Domain Display Name
                if "domainDisplayName" in data:
                    name = data["domainDisplayName"]
                    if name not in seen_strings:
                        strings_to_localize.append(f'        let _ = String(localized: "{escape_string(name)}", comment: "Domain Name")')
                        seen_strings.add(name)
                
                # Techniques
                if "techniques" in data:
                    for technique in data["techniques"]:
                        # Name
                        if "name" in technique:
                            t_name = technique["name"]
                            if t_name not in seen_strings:
                                strings_to_localize.append(f'        let _ = String(localized: "{escape_string(t_name)}", comment: "Technique Name")')
                                seen_strings.add(t_name)
                        
                        # Subtitle
                        if "subtitle" in technique:
                            t_sub = technique["subtitle"]
                            if t_sub not in seen_strings:
                                strings_to_localize.append(f'        let _ = String(localized: "{escape_string(t_sub)}", comment: "Technique Subtitle")')
                                seen_strings.add(t_sub)
                                
                        # Category (Optional, but visible in UI)
                        if "category" in technique:
                            t_cat = technique["category"]
                            if t_cat and t_cat not in seen_strings:
                                strings_to_localize.append(f'        let _ = String(localized: "{escape_string(t_cat)}", comment: "Category")')
                                seen_strings.add(t_cat)

                        # Steps
                        if "steps" in technique:
                            for step in technique["steps"]:
                                # Instruction
                                if "instruction" in step:
                                    s_inst = step["instruction"]
                                    if s_inst not in seen_strings:
                                        strings_to_localize.append(f'        let _ = String(localized: "{escape_string(s_inst)}", comment: "Step Instruction")')
                                        seen_strings.add(s_inst)
                                
                                # Help Detail
                                if "helpDetail" in step:
                                    s_help = step["helpDetail"]
                                    if s_help and s_help not in seen_strings:
                                        strings_to_localize.append(f'        let _ = String(localized: "{escape_string(s_help)}", comment: "Step Detail")')
                                        seen_strings.add(s_help)

        except Exception as e:
            print(f"Error processing {file_path}: {e}")

    # Write Swift File
    content = """import Foundation

// MARK: - Auto-Generated Localization Keys
// This file is generated by a script to ensure dynamic JSON content 
// is picked up by Xcode's String Catalog compiler.
// DO NOT CALL THIS METHOD.

enum ContentKeys {
    static func keepAlive() {
"""
    
    content += "\n".join(strings_to_localize)
    content += "\n    }\n}\n"

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Successfully generated {OUTPUT_FILE} with {len(strings_to_localize)} keys.")

if __name__ == "__main__":
    generate_swift_keys()
