// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Revive",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Revive",
            targets: ["AppModule"],
            bundleIdentifier: "com.revive.survival",
            teamIdentifier: "TJTDTMJ4TL",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Ember uses the microphone for hands-free voice commands."),
                .speechRecognition(purposeString: "Ember uses speech recognition to detect commands like 'next' or 'help'."),
                .locationWhenInUse(purposeString: "Revive uses your location to display GPS coordinates and Compass heading offline.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources",
            resources: [
                // .process("Resources/Assets.xcassets"), // Likely handled by folder structure or redundant
                .process("Resources/fire.json"),
                .process("Resources/shelter.json"),
                .process("Resources/water.json"),
                .process("Resources/food.json"),
                .process("Resources/firstaid.json"),
                .process("Resources/navigation.json"),
                .process("Resources/rescue.json"),
                .process("Resources/psychology.json"),
                .process("Resources/tools.json"),
                .process("Resources/environments.json"),
                .process("Resources/advanced_firstaid.json"),
                .process("Resources/advanced_tools.json"),
                .process("Resources/advanced_environments.json"),
                .process("Resources/hacks_general.json"),
                .process("Resources/rebuilding_civilization.json"),
                .process("Resources/Localizable.xcstrings")
            ]
        )
    ]
)