// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Revive",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Revive",
            targets: ["AppModule"],
            bundleIdentifier: "com.revive.survival",
            teamIdentifier: "TJTDTMJ4TL",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "Ember uses the microphone for hands-free voice commands."),
                .speechRecognition(purposeString: "Ember uses speech recognition to detect commands like 'next' or 'help'."),
                .appIntents(intentClasses: ["StartSirenIntent"], intentDefinitions: []),
                .backgroundAudio
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources",
            resources: [
                .process("Resources")
            ]
        )
    ]
)